package edu.duke.sj445.battleship;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import java.io.BufferedReader;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.PrintStream;
import java.io.Reader;
import java.io.StringReader;
import java.util.HashSet;

public class App {


  TextPlayer player1;
  TextPlayer player2;

  public App(TextPlayer A, TextPlayer B) {
    this.player1 = A;
    this.player2 = B;
  }


  public static void main(String[] args) throws IOException {

    Board<Character> b1 = new BattleShipBoard<Character>(10, 20, 'X');
    Board<Character> b2 = new BattleShipBoard<Character>(10, 20,'X');
    // InputStream in = System.in;
    // InputStreamReader isr = new InputStreamReader(in);
    BufferedReader input = new BufferedReader(new InputStreamReader(System.in));
    V2ShipFactory factory = new V2ShipFactory();
    TextPlayer a = new TextPlayer("A", b1, input, System.out, factory);
    TextPlayer b = new TextPlayer("B", b2, input, System.out, factory);
    App app = new App(a, b);
//    HashSet<Coordinate> diamond = a.getDiamond('R' - 'A', 8);
////    for(Coordinate c : diamond){
////      char ch = (char)(c.getRow() + 'a');
////      System.out.println(ch + "," + c.getColumn());
////    }
    app.doPlacementPhase();
    app.doAttackingPhase();
    //p,7
    //p,9
    //p,8
    //q,6
    //s,9
    //s,8
    //q,9
    //s,7
    //q,8
    //s,6
    //o,8
    //q,7
    //t,7
    //t,9
    //t,8
  }

  public void doPlacementPhase() throws IOException {
    player1.doPlacementPhase();
    player2.doPlacementPhase();
  }

  public void doAttackingPhase() throws IOException {
    while (true){
      player1.playOneTurn(player2.theBoard, player2.name);
      if (player2.theBoard.checkAllSunk() == true) {
        System.out.println("Great, Player " + player1.name + " you win!");
        break;
      }
      player2.playOneTurn(player1.theBoard, player1.name);
      if (player1.theBoard.checkAllSunk() == true) {
        System.out.println("Great, Player " + player2.name + " you win!");
        break;
      }
    }
  }


}
